apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
  labels: 
    app: foodtrucks
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: foodtrucks
    spec:
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
  selector: 
    matchLabels:
      app: foodtrucks
