apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodtruck-deployment
  labels:
    app: foodtrucks 
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: foodtrucks
    spec: 
      containers:
        - name: foodtruck-python
          image: prakhar1989/foodtrucks-web
  selector: 
    matchLabels:
      app: foodtrucks

---

apiVersion: v1 
kind: Service
metadata:
  name: foodtruck-deployment
  labels:
    app: foodtrucks
spec:
  
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: foodtrucks
