apiVersion: apps/v1
kind: Deployment
metadata:
  name: catgif-deployment
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: catgif
          image: prakhar1989/catnip
          ports:
            - containerPort: 5000
  replicas: 1
